catalogue_host: catalogue.robosyed.space
cart_host: cart.robosyed.space
shipping_host: shipping.robosyed.space
dipatch_host: dispatch.robosyed.space
user_host: user.robosyed.space
payment_host: payment.robosyed.space
